apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      serviceAccountName: chat-backend-sa
      terminationGracePeriodSeconds: 5
      containers:
        - name: chat-backend
          image: 192.168.30.10:5000/chat-backend:agent-k8s-client-1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: deepseek-secret
---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend
spec:
  selector:
    app: chat-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP